name: flutter_clean_arch
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  # Functional programming thingies
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Service locator
  get_it: ^7.2.0
  # Local cache
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  mockito: ^5.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
